# ----
# Site

title: The HIDIOT
url: "https://docs.hidiot.com"
baseurl:
google_analytics: UA-97379221-3
show_full_navigation: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Documentation for using the HIDIOT
author:
  name: Raw Hex
  email: hidiot@rawhex.com
  twitter: rawhex
social:
  name: Raw Hex
  links:
    - https://hidiot.com
    - https://github.com/rawhex/hidiot
    - https://facebook.com/rawhex
    - https://rawhex.com

# -----
# Build

permalink: pretty

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - vendor/bundle

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true
  prototype:
    title: Prototype Documentation
    permalink: /prototypes/:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
  # -
  #   scope:
  #     path: ""
  #     type: "posts"
  #   values:
  #     _comments:
  #       type: Marks the impact of this release

# -----------
# CloudCannon

types:
  - minor
  - major
